[2025-03-17T20:08:14.362+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-17T20:08:14.396+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.accurate manual__2025-03-17T20:08:10.064598+00:00 [queued]>
[2025-03-17T20:08:14.408+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.accurate manual__2025-03-17T20:08:10.064598+00:00 [queued]>
[2025-03-17T20:08:14.411+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-17T20:08:14.431+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): accurate> on 2025-03-17 20:08:10.064598+00:00
[2025-03-17T20:08:14.442+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=280) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T20:08:14.444+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'accurate', 'manual__2025-03-17T20:08:10.064598+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmppetkk_xy']
[2025-03-17T20:08:14.446+0000] {standard_task_runner.py:63} INFO - Started process 281 to run task
[2025-03-17T20:08:14.447+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask accurate
[2025-03-17T20:08:14.505+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.accurate manual__2025-03-17T20:08:10.064598+00:00 [running]> on host 7ed0592ccd5e
[2025-03-17T20:08:14.603+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='accurate' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T20:08:10.064598+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-17T20:08:10.064598+00:00'
[2025-03-17T20:08:14.604+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-17T20:08:14.626+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-17T20:08:14.628+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'accurate'"]
[2025-03-17T20:08:14.642+0000] {subprocess.py:86} INFO - Output:
[2025-03-17T20:08:14.645+0000] {subprocess.py:93} INFO - accurate
[2025-03-17T20:08:14.646+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-03-17T20:08:14.647+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-17T20:08:14.680+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=accurate, run_id=manual__2025-03-17T20:08:10.064598+00:00, execution_date=20250317T200810, start_date=20250317T200814, end_date=20250317T200814
[2025-03-17T20:08:14.702+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-17T20:08:14.717+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T20:08:14.726+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
